title: "DevOps Malayalam"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/web"
permalink: "/:title/"
logo: 'assets/images/devopslogo-v1.png'
favicon: 'assets/images/favicon.ico'
author: Alexy
paginate: 8
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  alexy:
    name: Alexy
    display_name: Alexy
    avatar: 'assets/images/sal.png'
    email: devopskerala@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  sibin:
    name: Sibin
    display_name: Sibin
    avatar: 'assets/images/john.png'
    email: devopskerala@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  linkedin: https://www.linkedin.com/company/devopsmalayalam
  telegram: https://t.me/joinchat/tninMc2bBGdiY2E1
  slack: https://join.slack.com/t/devopsmalayalam/shared_invite/zt-tuws4bts-9ZhKh5snDTuv8m7FiECv~g)

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
